# 0-D Tensors/Scalers

In [1]:
import numpy as np

In [3]:
a=np.array(2)

In [4]:
a

array(2)

In [5]:
a.ndim

0

# 1-D Tensors/Vector

In [6]:
arr=np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

# 2-D Tensors/Matricx

In [9]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mat.ndim

2

# 3-D Tensors

In [4]:
import numpy as np

In [5]:
ten=np.array([[[1,2,3],
              [4,5,6]],
            [[11,22,33],
             [44,55,66]]])

In [6]:
ten

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [7]:
ten.ndim

3